# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
#    manager:
#        name: TinyDB
#        connection: /tmp/pygeoapi-process-manager.db
#        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net
    
logging:
    level: DEBUG
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: AquaInfra processing services
        description:
            en: An OGC conformant API to AquaInfra processing services
        keywords:
            en:
                - geospatial
                - data
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license (TODO check)
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Leibniz Institute for Freshwater Ecology and Inland Fisheries (FVB-IGB), Berlin
        url: https://igb-berlin.de
    contact:
        name: Buurman, Merret
        position: Scientific Staff
        address: Müggelseedamm 310
        city: Berlin
        stateorprovince: Berlin
        postalcode: 12587
        country: Germany
        email: merret.buurman@igb-berlin.de
        url: https://glowabio.org/
        role: pointOfContact

resources:

    snap-to-network:
        type: process
        processor:
            name: SnapToNetwork

    get-species-data:
        type: process
        processor:
            name: GetSpeciesData

    get-drainage-basin:
        type: process
        processor:
            name: GetDrainageBasin

    get-dams-fhred:
        type: process
        processor:
            name: GetDamFHReD

    get-dams-grand:
        type: process
        processor:
            name: GetDamGRanD


